---
driver:
  name: ec2
  aws_ssh_key_id: will
  reigon: us-east-1
  availability_zone: c
  subnet_id: subnet-5430ea7f
  associate_public_ip: true
  instance_type: t2.micro
  security_group_ids: ["sg-4e128c36", "sg-af5dedd5"]

transport:
  ssh_key: ~/.ssh/will
  connection_retries: 5

provisioner:
  name: chef_zero

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[homework::default]
    attributes:
      homework:
        database:
          admin_password: 'postgres_admin_password'
